// This file is generated by Firebase Genkit.
// THIS IS AN AUTOGENERATED FILE! Do not edit.
'use server';
/**
 * @fileOverview A resume creation AI agent.
 *
 * - resumeFromPrompt - A function that handles the resume creation process.
 * - ResumeFromPromptInput - The input type for the resumeFromPrompt function.
 * - ResumeFromPromptOutput - The return type for the resumeFromPrompt function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const ResumeFromPromptInputSchema = z.object({
  prompt: z.string().describe('A prompt describing the desired resume, including details like skills, experience, and education.'),
});
export type ResumeFromPromptInput = z.infer<typeof ResumeFromPromptInputSchema>;

const ResumeFromPromptOutputSchema = z.object({
  resume: z.string().describe('The generated resume in a professional format, such as text or markdown.'),
});
export type ResumeFromPromptOutput = z.infer<typeof ResumeFromPromptOutputSchema>;

export async function resumeFromPrompt(input: ResumeFromPromptInput): Promise<ResumeFromPromptOutput> {
  return resumeFromPromptFlow(input);
}

const prompt = ai.definePrompt({
  name: 'resumeFromPromptPrompt',
  input: {schema: ResumeFromPromptInputSchema},
  output: {schema: ResumeFromPromptOutputSchema},
  prompt: `You are an expert resume writer. Please generate a professional-looking resume based on the following description:

{{{prompt}}}

Please ensure the resume is well-formatted and easy to read.
`,
});

const resumeFromPromptFlow = ai.defineFlow(
  {
    name: 'resumeFromPromptFlow',
    inputSchema: ResumeFromPromptInputSchema,
    outputSchema: ResumeFromPromptOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
